

ERROR_NO_FILE = "No input file specified and no data piped."
ERROR_CONVERSION_FAILED = "XML conversion failed."
ERROR_READ_STDIN = "Could not read from standard input."
ERROR_FILE_NOT_FOUND = "File not found: {}"
ERROR_READ_FILE = "Could not read file: {}"
ERROR_WRITE_FILE = "Could not write to file: {}"
ERROR_NO_FILE_UPLOADED = "No file uploaded."
ERROR_NO_FILENAME_SET = "No filename specified"
ERROR_READ_UPLOADED_FILE = "Could not read uploaded file"
ERROR_INVALID_PTAF_TAG = "Invalid PTAF tag: {}"
ERROR_INVALID_PTAF_TAG_ORDER = "Invalid PTAF tag order."

CLI_DESCRIPTION = "Convert text file in PTAF format to XML."
CLI_PRETTY = "Enable pretty print for XML output (default: enabled)"
CLI_NO_PRETTY = "Disable pretty print for XML output"
CLI_INPUT_FILE_PATH = "Path to the input text file (default: read from standard input)"
CLI_INPUT_FILE_ENCODING = "Encoding of the input file (default: utf-8)"
CLI_OUTPUT_FILE_PATH = "Path to the output XML file (default: write to standard output)"
CLI_SERVE = "Run application as a server"

PTAF_SEPARATOR = "|"
PTAF_TAG_PERSON = "P"
PTAF_TAG_TELEPHONE = "T"
PTAF_TAG_ADDRESS = "A"
PTAF_TAG_FAMILY = "F"
INPUT_FILE_DEFAULT_ENCODING = "utf-8"

XML_INDENTATION = "    "
XML_TAG_PEOPLE = "people"
XML_TAG_PERSON = "person"
XML_TAG_PERSON_FIRSTNAME = "firstname"
XML_TAG_PERSON_LASTNAME = "lastname"
XML_TAG_FAMILY = "family"
XML_TAG_FAMILY_NAME = "name"
XML_TAG_FAMILY_BORN = "born"
XML_TAG_TELEPHONE = "phone"
XML_TAG_TELEPHONE_MOBILE = "mobile"
XML_TAG_TELEPHONE_HOME = "home"
XML_TAG_ADDRESS = "address"
XML_TAG_ADDRESS_STREET = "street"
XML_TAG_ADDRESS_CITY = "city"
XML_TAG_ADDRESS_ZIPCODE = "zipcode"
OUTPUT_FILE_ENCODING = "utf-8"